name: throne
description: simple package to help with loading async instances before starting the app
version: 0.0.1
author: ahmed masoud
homepage: https://www.facebook.com/maxzod66
environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.12+4
  flutter_secure_storage: ^3.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: